package com.yascn.smartpark;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yascn.smartpark.bean.GreenDaoCarLicense;
import com.yascn.smartpark.bean.JPush;
import com.yascn.smartpark.bean.SearchGaodeHistoryBean;
import com.yascn.smartpark.bean.SearchHistoryDaoBean;

import com.yascn.smartpark.GreenDaoCarLicenseDao;
import com.yascn.smartpark.JPushDao;
import com.yascn.smartpark.SearchGaodeHistoryBeanDao;
import com.yascn.smartpark.SearchHistoryDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoCarLicenseDaoConfig;
    private final DaoConfig jPushDaoConfig;
    private final DaoConfig searchGaodeHistoryBeanDaoConfig;
    private final DaoConfig searchHistoryDaoBeanDaoConfig;

    private final GreenDaoCarLicenseDao greenDaoCarLicenseDao;
    private final JPushDao jPushDao;
    private final SearchGaodeHistoryBeanDao searchGaodeHistoryBeanDao;
    private final SearchHistoryDaoBeanDao searchHistoryDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoCarLicenseDaoConfig = daoConfigMap.get(GreenDaoCarLicenseDao.class).clone();
        greenDaoCarLicenseDaoConfig.initIdentityScope(type);

        jPushDaoConfig = daoConfigMap.get(JPushDao.class).clone();
        jPushDaoConfig.initIdentityScope(type);

        searchGaodeHistoryBeanDaoConfig = daoConfigMap.get(SearchGaodeHistoryBeanDao.class).clone();
        searchGaodeHistoryBeanDaoConfig.initIdentityScope(type);

        searchHistoryDaoBeanDaoConfig = daoConfigMap.get(SearchHistoryDaoBeanDao.class).clone();
        searchHistoryDaoBeanDaoConfig.initIdentityScope(type);

        greenDaoCarLicenseDao = new GreenDaoCarLicenseDao(greenDaoCarLicenseDaoConfig, this);
        jPushDao = new JPushDao(jPushDaoConfig, this);
        searchGaodeHistoryBeanDao = new SearchGaodeHistoryBeanDao(searchGaodeHistoryBeanDaoConfig, this);
        searchHistoryDaoBeanDao = new SearchHistoryDaoBeanDao(searchHistoryDaoBeanDaoConfig, this);

        registerDao(GreenDaoCarLicense.class, greenDaoCarLicenseDao);
        registerDao(JPush.class, jPushDao);
        registerDao(SearchGaodeHistoryBean.class, searchGaodeHistoryBeanDao);
        registerDao(SearchHistoryDaoBean.class, searchHistoryDaoBeanDao);
    }
    
    public void clear() {
        greenDaoCarLicenseDaoConfig.getIdentityScope().clear();
        jPushDaoConfig.getIdentityScope().clear();
        searchGaodeHistoryBeanDaoConfig.getIdentityScope().clear();
        searchHistoryDaoBeanDaoConfig.getIdentityScope().clear();
    }

    public GreenDaoCarLicenseDao getGreenDaoCarLicenseDao() {
        return greenDaoCarLicenseDao;
    }

    public JPushDao getJPushDao() {
        return jPushDao;
    }

    public SearchGaodeHistoryBeanDao getSearchGaodeHistoryBeanDao() {
        return searchGaodeHistoryBeanDao;
    }

    public SearchHistoryDaoBeanDao getSearchHistoryDaoBeanDao() {
        return searchHistoryDaoBeanDao;
    }

}
