package com.yascn.smartpark;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yascn.smartpark.bean.GreenDaoCarLicense;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_DAO_CAR_LICENSE".
*/
public class GreenDaoCarLicenseDao extends AbstractDao<GreenDaoCarLicense, Long> {

    public static final String TABLENAME = "GREEN_DAO_CAR_LICENSE";

    /**
     * Properties of entity GreenDaoCarLicense.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CarLicense = new Property(1, String.class, "carLicense", false, "CAR_LICENSE");
    };


    public GreenDaoCarLicenseDao(DaoConfig config) {
        super(config);
    }
    
    public GreenDaoCarLicenseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_DAO_CAR_LICENSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CAR_LICENSE\" TEXT);"); // 1: carLicense
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_DAO_CAR_LICENSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenDaoCarLicense entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String carLicense = entity.getCarLicense();
        if (carLicense != null) {
            stmt.bindString(2, carLicense);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenDaoCarLicense entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String carLicense = entity.getCarLicense();
        if (carLicense != null) {
            stmt.bindString(2, carLicense);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GreenDaoCarLicense readEntity(Cursor cursor, int offset) {
        GreenDaoCarLicense entity = new GreenDaoCarLicense( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // carLicense
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenDaoCarLicense entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCarLicense(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GreenDaoCarLicense entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GreenDaoCarLicense entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
